### PR TITLE
Create it.js

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by holtwick** [comment]
Mille grazie. Usate la pagna peer.school?

**Comment by holtwick** [comment]
I updated the project to use your translation. Thanks!

**Comment by albanobattistella** [comment]
> Mille grazie. Usate la pagina peer.school?

yes, we using. I saw that the project is suspended, is it true?
it's a beautiful project and should grow with some new whiteboard features like adding shapes, objects, brushes, etc.

**Comment by holtwick** [comment]
Ciao @albanobattistella Yes indeed I'm currently not putting much effort into the project any more, because I had the impression it was not used that much. Instead I continued video conferencing efforts in https://brie.fi/ng Of course some stuff could again be ported back to peer.school if there was some more traction on the project.

Is it used in a a school environment or something else? Did you also consider using https://bigbluebutton.org/ ? I would love to know more about how it is used.

**Comment by DigitEgal** [comment]
yeah finally ich hab dich gefunden, Warst du nicht ebenfalls beim #WirVsVirus Hackaton dabei? 👍 

Ich bin auch interessiert daran den code zu nutzen - ebenfalls für Bildungs-Zwecke. Allerdings will ich das ganze in andere Systeme einbetten um zeitgleiche sowohl zeitunabhängige kollaboration zu ermöglichen. Würd gern mal mit dir quatschen. mfg Christian --- Email: [Christian@digitegal.de](url)

**Comment by holtwick** [comment]
Hi @DigitEgal I'll write you via email.

**Pull request merged**
